wipe git user config in CI before tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,6 +31,15 @@ jobs:
     - name: lint with ruff
       run: ruff src
 
+    # need this to detect cases where git commands require user and would fail without one
+    - name: wipe git user config
+      run: |
+        set -ex
+        git config user.name
+        git config user.name ""
+        git config user.email
+        git config user.email ""
+
     - name: unit tests
       run: |
         pytest test/unit/ test/component/ --cov --cov-report xml
